### ISSUE TITLE
Pushing back VR test results - link no longer works

### ISSUE THREAD

**Issue by mariacha** [kporras07/tbt-ci-integrations#20]
I opened an issue for this on the Example Drops repo, but maybe this is the right place for it? https://github.com/pantheon-systems/example-drops-8-composer/issues/562

If this is the right place to provide the PR for a fix, I'm happy to do it. Or maybe it's not happening for others and it's something odd about our setup?

**Comment by vinmassaro** [comment]
@mariacha check out the PR here: https://github.com/pantheon-systems/tbt-ci-templates/pull/18

**Comment by mariacha** [comment]
That's slightly different -- we do still get the comment on the PR "Visual regressions passed/failed" but the link itself doesn't work anymore. 

You can see it in practice on the example drops repo:
https://github.com/pantheon-systems/example-drops-8-composer/pull/597

that link to the build artifacts is a 404:
https://8294-71170282-gh.circle-artifacts.com/0/artifacts/backstop_data/html_report/index.html

**Comment by mariacha** [comment]
I went ahead and made the PR: https://github.com/pantheon-systems/tbt-ci-templates/pull/21

**Comment by kporras07** [comment]
PR merged. Thanks!
